image: java:17-jdk

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script: ./gradlew build -x test
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - main

deploy-to-ec2:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - scp -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" ./build/libs/*.jar ec2-user@"$DEPLOY_SERVER":~/studious-backend/build/libs/*.jar
    - ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" ec2-user@"$DEPLOY_SERVER" 'bash ~/test-cd.sh'
  only:
    - main
